#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFlow.Dataverse.DataModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum AAr_Account_AAr_ConsumerStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Current", 2)]
		Current = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Deleted", 4)]
		Deleted = 50,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Finalled", 3)]
		Finalled = 40,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Future", 1)]
		Future = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Pending", 0)]
		Pending = 10,
	}
	
	/// <summary>
	/// Status of the Account
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum AAr_Account_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0)]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1)]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Account
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum AAr_Account_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Current", 3)]
		Current = 745620002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Deleted", 4)]
		Deleted = 745620003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Finalled", 1)]
		Finalled = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Future", 2)]
		Future = 745620001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Pending", 0)]
		Pending = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("aar_account")]
	public partial class AAr_Account : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the aar_account entity
		/// </summary>
		public partial class Fields
		{
			public const string AAr_AccountActiveDate = "aar_accountactivedate";
			public const string AAr_AccountAddress = "aar_accountaddress";
			public const string AAr_AccountAddressName = "aar_accountaddressname";
			public const string AAr_AccountBalance = "aar_accountbalance";
			public const string AAr_AccountBalance_Base = "aar_accountbalance_base";
			public const string AAr_AccountClosuredAte = "aar_accountclosuredate";
			public const string AAr_AccountClosureReason = "aar_accountclosurereason";
			public const string AAr_AccountClosureReasonName = "aar_accountclosurereasonname";
			public const string AAr_AccountId = "aar_accountid";
			public const string Id = "aar_accountid";
			public const string AAr_AccountName = "aar_accountname";
			public const string AAr_AccountNumber = "aar_accountnumber";
			public const string AAr_AccountType = "aar_accounttype";
			public const string AAr_AccountTypeName = "aar_accounttypename";
			public const string AAr_AcDate = "aar_acdate";
			public const string AAr_AddressValidationMessage = "aar_addressvalidationmessage";
			public const string AAr_AddressValidationTimestamp = "aar_addressvalidationtimestamp";
			public const string AAr_BalanceOverdue = "aar_balanceoverdue";
			public const string AAr_BalanceOverdue_Base = "aar_balanceoverdue_base";
			public const string AAr_ConsumerStatus = "aar_consumerstatus";
			public const string AAr_ConsumerStatusName = "aar_consumerstatusname";
			public const string AAr_CoUntoFactiveFlags = "aar_countofactiveflags";
			public const string AAr_CoUntoFactiveFlags_Date = "aar_countofactiveflags_date";
			public const string AAr_CoUntoFactiveFlags_State = "aar_countofactiveflags_state";
			public const string AAr_CreditCodes = "aar_creditcodes";
			public const string AAr_CreditControlCycle = "aar_creditcontrolcycle";
			public const string AAr_CreditControlCycleAmount = "aar_creditcontrolcycleamount";
			public const string AAr_CreditControlCycleAmount_Base = "aar_creditcontrolcycleamount_base";
			public const string AAr_CreditControlCycleNextAction = "aar_creditcontrolcyclenextaction";
			public const string AAr_CreditReference = "aar_creditreference";
			public const string AAr_CreditRisk = "aar_creditrisk";
			public const string AAr_CreditStatus = "aar_creditstatus";
			public const string AAr_CurrentBillingPeriodEndDate = "aar_currentbillingperiodenddate";
			public const string AAr_CurrentBillingPeriodStartDate = "aar_currentbillingperiodstartdate";
			public const string AAr_CurrentBillingPeriodTotalDays = "aar_currentbillingperiodtotaldays";
			public const string AAr_CurrentBundle = "aar_currentbundle";
			public const string AAr_CurrentBundleName = "aar_currentbundlename";
			public const string AAr_CurrentContract = "aar_currentcontract";
			public const string AAr_CurrentContractName = "aar_currentcontractname";
			public const string AAr_CurrentPaymentArrangement = "aar_currentpaymentarrangement";
			public const string AAr_CurrentPaymentArrangementName = "aar_currentpaymentarrangementname";
			public const string AAr_CurrentPostalAddress = "aar_currentpostaladdress";
			public const string AAr_CurrentPostalAddressName = "aar_currentpostaladdressname";
			public const string AAr_CurrentRebateEndDate = "aar_currentrebateenddate";
			public const string AAr_CurrentRebateName = "aar_currentrebatename";
			public const string AAr_CurrentRebateStartDate = "aar_currentrebatestartdate";
			public const string AAr_CurrentUsage = "aar_currentusage";
			public const string AAr_CustomerRoles_Account_AAr_Account = "AAr_CustomerRoles_Account_AAr_Account";
			public const string AAr_DeemedBetterOfferAmount = "aar_deemedbetterofferamount";
			public const string AAr_DeemedBetterOfferAmount_Base = "aar_deemedbetterofferamount_base";
			public const string AAr_DisconnectionNonpayment = "aar_disconnectionnonpayment";
			public const string AAr_DisconnectionNonpaymentName = "aar_disconnectionnonpaymentname";
			public const string AAr_EligibleRefundAmount = "aar_eligiblerefundamount";
			public const string AAr_EligibleRefundAmount_Base = "aar_eligiblerefundamount_base";
			public const string AAr_EntryDate = "aar_entrydate";
			public const string AAr_FamilyViolence = "aar_familyviolence";
			public const string AAr_FamilyViolenceName = "aar_familyviolencename";
			public const string AAr_Install = "aar_install";
			public const string AAr_InstallAddress = "aar_installaddress";
			public const string AAr_InstallFullAddress = "aar_installfulladdress";
			public const string AAr_InstallName = "aar_installname";
			public const string AAr_InstallSiteType = "aar_installsitetype";
			public const string AAr_InstallSiteTypeName = "aar_installsitetypename";
			public const string AAr_InvoiceReference = "aar_invoicereference";
			public const string AAr_LastBillDate = "aar_lastbilldate";
			public const string AAr_LastEffectiveDateOfAddress = "aar_lasteffectivedateofaddress";
			public const string AAr_LastInvoicedAte = "aar_lastinvoicedate";
			public const string AAr_LastMeterReaddAte = "aar_lastmeterreaddate";
			public const string AAr_LastMeterReadType = "aar_lastmeterreadtype";
			public const string AAr_LastMeterReadTypeName = "aar_lastmeterreadtypename";
			public const string AAr_LifeSupportRequired = "aar_lifesupportrequired";
			public const string AAr_LifeSupportRequiredName = "aar_lifesupportrequiredname";
			public const string AAr_LpMerchant = "aar_lpmerchant";
			public const string AAr_LpMerchantName = "aar_lpmerchantname";
			public const string AAr_ManagingOfficer = "aar_managingofficer";
			public const string AAr_MeterClass = "aar_meterclass";
			public const string AAr_MoveOutdate = "aar_moveoutdate";
			public const string AAr_MoveOutFeesWaived = "aar_moveoutfeeswaived";
			public const string AAr_MoveOutFeesWaivedName = "aar_moveoutfeeswaivedname";
			public const string AAr_MoveOutFinalBillEmail = "aar_moveoutfinalbillemail";
			public const string AAr_MoveOutFinalBillMethod = "aar_moveoutfinalbillmethod";
			public const string AAr_MoveOutFinalBillMethodName = "aar_moveoutfinalbillmethodname";
			public const string AAr_MoveOutFinalBillPostal = "aar_moveoutfinalbillpostal";
			public const string AAr_MoveOutNotes = "aar_moveoutnotes";
			public const string AAr_MoveOutreason = "aar_moveoutreason";
			public const string AAr_NetworkTariffCode = "aar_networktariffcode";
			public const string AAr_NextInvoicedAte = "aar_nextinvoicedate";
			public const string AAr_NextPaymentDueDate = "aar_nextpaymentduedate";
			public const string AAr_NextScheduledMeterRead = "aar_nextscheduledmeterread";
			public const string AAr_NextStage = "aar_nextstage";
			public const string AAr_Offer = "aar_offer";
			public const string AAr_OfferName = "aar_offername";
			public const string AAr_PaymentExtensionDue = "aar_paymentextensiondue";
			public const string AAr_PaymentExtensionInPlace = "aar_paymentextensioninplace";
			public const string AAr_PaymentExtensionInPlaceName = "aar_paymentextensioninplacename";
			public const string AAr_PaymentReference = "aar_paymentreference";
			public const string AAr_PricingPlan = "aar_pricingplan";
			public const string AAr_PrincipalCustomerId = "aar_principalcustomerid";
			public const string AAr_PrincipalCustomerName = "aar_principalcustomername";
			public const string AAr_RiskScore = "aar_riskscore";
			public const string AAr_SalesChannel = "aar_saleschannel";
			public const string AAr_SalesChannelName = "aar_saleschannelname";
			public const string AAr_SignupApplication = "aar_signupapplication";
			public const string AAr_SignupApplicationName = "aar_signupapplicationname";
			public const string AAr_TransactionHistoryUrl = "aar_transactionhistoryurl";
			public const string AAr_UsageAtLastMeterRead = "aar_usageatlastmeterread";
			public const string AAr_UsageForSamePeriodLastYear = "aar_usageforsameperiodlastyear";
			public const string AAr_UtilityService = "aar_utilityservice";
			public const string AAr_UtilityServiceName = "aar_utilityservicename";
			public const string AAr_VelocityBestOfferId = "aar_velocitybestofferid";
			public const string AAr_VelocityConsumerId = "aar_velocityconsumerid";
			public const string AAr_VelocityLedgerId = "aar_velocityledgerid";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string ExchangerAte = "exchangerate";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StateCodename = "statecodename";
			public const string StatusCode = "statuscode";
			public const string StatusCodename = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string TransactionCurrencyIdName = "transactioncurrencyidname";
			public const string UtcConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public AAr_Account(System.Guid id) : 
				base(EntityLogicalName, id)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public AAr_Account(string keyName, object keyValue) : 
				base(EntityLogicalName, keyName, keyValue)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public AAr_Account(Microsoft.Xrm.Sdk.KeyAttributeCollection keyAttributes) : 
				base(EntityLogicalName, keyAttributes)
		{
		}
		
		public const string AlternateKeys = "aar_accountnumber";
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public AAr_Account() : 
				base(EntityLogicalName)
		{
		}
		
		public const string PrimaryIdAttribute = "aar_accountid";
		
		public const string PrimaryNameAttribute = "aar_accountname";
		
		public const string EntitySchemaName = "aar_Account";
		
		public const string EntityLogicalName = "aar_account";
		
		public const string EntityLogicalCollectionName = "aar_accounts";
		
		public const string EntitySetName = "aar_accounts";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_accountactivedate")]
		public System.Nullable<System.DateTime> AAr_AccountActiveDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aar_accountactivedate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_accountactivedate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_accountaddress")]
		public Microsoft.Xrm.Sdk.EntityReference AAr_AccountAddress
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("aar_accountaddress");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_accountaddress", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_accountaddressname")]
		public string AAr_AccountAddressName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_accountaddress"))
				{
					return this.FormattedValues["aar_accountaddress"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_accountbalance")]
		public Microsoft.Xrm.Sdk.Money AAr_AccountBalance
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("aar_accountbalance");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_accountbalance", value);
			}
		}
		
		/// <summary>
		/// Value of the Account Balance in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_accountbalance_base")]
		public Microsoft.Xrm.Sdk.Money AAr_AccountBalance_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("aar_accountbalance_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_accountclosuredate")]
		public System.Nullable<System.DateTime> AAr_AccountClosuredAte
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aar_accountclosuredate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_accountclosuredate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_accountclosurereason")]
		public virtual AAr_AccountClosureReason? AAr_AccountClosureReason
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((AAr_AccountClosureReason?)(EntityOptionSetEnum.GetEnum(this, "aar_accountclosurereason")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_accountclosurereason", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_accountclosurereasonname")]
		public string AAr_AccountClosureReasonName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_accountclosurereason"))
				{
					return this.FormattedValues["aar_accountclosurereason"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_accountid")]
		public System.Nullable<System.Guid> AAr_AccountId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("aar_accountid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_accountid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_accountid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.AAr_AccountId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_accountname")]
		public string AAr_AccountName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_accountname");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_accountname", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_accountnumber")]
		public string AAr_AccountNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_accountnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_accountnumber", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_accounttype")]
		public virtual AAr_AccountType? AAr_AccountType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((AAr_AccountType?)(EntityOptionSetEnum.GetEnum(this, "aar_accounttype")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_accounttype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_accounttypename")]
		public string AAr_AccountTypeName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_accounttype"))
				{
					return this.FormattedValues["aar_accounttype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Velocity Account Holder Since Date
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_acdate")]
		public System.Nullable<System.DateTime> AAr_AcDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aar_acdate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_acdate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_addressvalidationmessage")]
		public string AAr_AddressValidationMessage
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_addressvalidationmessage");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_addressvalidationmessage", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_addressvalidationtimestamp")]
		public System.Nullable<System.DateTime> AAr_AddressValidationTimestamp
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aar_addressvalidationtimestamp");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_addressvalidationtimestamp", value);
			}
		}
		
		/// <summary>
		/// Replaced with API call to calculate the balance overdue amount
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_balanceoverdue")]
		public Microsoft.Xrm.Sdk.Money AAr_BalanceOverdue
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("aar_balanceoverdue");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_balanceoverdue", value);
			}
		}
		
		/// <summary>
		/// Value of the Balance Overdue in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_balanceoverdue_base")]
		public Microsoft.Xrm.Sdk.Money AAr_BalanceOverdue_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("aar_balanceoverdue_base");
			}
		}
		
		/// <summary>
		/// The status from the Consumer record in Velocity. Consumer is 1:1 with Account so we can retrieve status from there.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_consumerstatus")]
		public virtual AAr_Account_AAr_ConsumerStatus? AAr_ConsumerStatus
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((AAr_Account_AAr_ConsumerStatus?)(EntityOptionSetEnum.GetEnum(this, "aar_consumerstatus")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_consumerstatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_consumerstatusname")]
		public string AAr_ConsumerStatusName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_consumerstatus"))
				{
					return this.FormattedValues["aar_consumerstatus"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_countofactiveflags")]
		public System.Nullable<int> AAr_CoUntoFactiveFlags
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("aar_countofactiveflags");
			}
		}
		
		/// <summary>
		/// Last Updated time of rollup field Count of Active Flags.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_countofactiveflags_date")]
		public System.Nullable<System.DateTime> AAr_CoUntoFactiveFlags_Date
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aar_countofactiveflags_date");
			}
		}
		
		/// <summary>
		/// State of rollup field Count of Active Flags.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_countofactiveflags_state")]
		public System.Nullable<int> AAr_CoUntoFactiveFlags_State
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("aar_countofactiveflags_state");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_creditcodes")]
		public string AAr_CreditCodes
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_creditcodes");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_creditcodes", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_creditcontrolcycle")]
		public string AAr_CreditControlCycle
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_creditcontrolcycle");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_creditcontrolcycle", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_creditcontrolcycleamount")]
		public Microsoft.Xrm.Sdk.Money AAr_CreditControlCycleAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("aar_creditcontrolcycleamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_creditcontrolcycleamount", value);
			}
		}
		
		/// <summary>
		/// Value of the Credit Control Cycle Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_creditcontrolcycleamount_base")]
		public Microsoft.Xrm.Sdk.Money AAr_CreditControlCycleAmount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("aar_creditcontrolcycleamount_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_creditcontrolcyclenextaction")]
		public System.Nullable<System.DateTime> AAr_CreditControlCycleNextAction
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aar_creditcontrolcyclenextaction");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_creditcontrolcyclenextaction", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_creditreference")]
		public string AAr_CreditReference
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_creditreference");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_creditreference", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_creditrisk")]
		public string AAr_CreditRisk
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_creditrisk");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_creditrisk", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_creditstatus")]
		public string AAr_CreditStatus
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_creditstatus");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_creditstatus", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_currentbillingperiodenddate")]
		public System.Nullable<System.DateTime> AAr_CurrentBillingPeriodEndDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aar_currentbillingperiodenddate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_currentbillingperiodenddate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_currentbillingperiodstartdate")]
		public System.Nullable<System.DateTime> AAr_CurrentBillingPeriodStartDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aar_currentbillingperiodstartdate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_currentbillingperiodstartdate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_currentbillingperiodtotaldays")]
		public System.Nullable<int> AAr_CurrentBillingPeriodTotalDays
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("aar_currentbillingperiodtotaldays");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_currentbundle")]
		public Microsoft.Xrm.Sdk.EntityReference AAr_CurrentBundle
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("aar_currentbundle");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_currentbundle", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_currentbundlename")]
		public string AAr_CurrentBundleName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_currentbundle"))
				{
					return this.FormattedValues["aar_currentbundle"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_currentcontract")]
		public Microsoft.Xrm.Sdk.EntityReference AAr_CurrentContract
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("aar_currentcontract");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_currentcontract", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_currentcontractname")]
		public string AAr_CurrentContractName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_currentcontract"))
				{
					return this.FormattedValues["aar_currentcontract"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_currentpaymentarrangement")]
		public Microsoft.Xrm.Sdk.EntityReference AAr_CurrentPaymentArrangement
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("aar_currentpaymentarrangement");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_currentpaymentarrangement", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_currentpaymentarrangementname")]
		public string AAr_CurrentPaymentArrangementName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_currentpaymentarrangement"))
				{
					return this.FormattedValues["aar_currentpaymentarrangement"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_currentpostaladdress")]
		public Microsoft.Xrm.Sdk.EntityReference AAr_CurrentPostalAddress
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("aar_currentpostaladdress");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_currentpostaladdress", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_currentpostaladdressname")]
		public string AAr_CurrentPostalAddressName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_currentpostaladdress"))
				{
					return this.FormattedValues["aar_currentpostaladdress"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_currentrebateenddate")]
		public System.Nullable<System.DateTime> AAr_CurrentRebateEndDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aar_currentrebateenddate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_currentrebateenddate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_currentrebatename")]
		public string AAr_CurrentRebateName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_currentrebatename");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_currentrebatename", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_currentrebatestartdate")]
		public System.Nullable<System.DateTime> AAr_CurrentRebateStartDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aar_currentrebatestartdate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_currentrebatestartdate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_currentusage")]
		public System.Nullable<int> AAr_CurrentUsage
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("aar_currentusage");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_currentusage", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_deemedbetterofferamount")]
		public Microsoft.Xrm.Sdk.Money AAr_DeemedBetterOfferAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("aar_deemedbetterofferamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_deemedbetterofferamount", value);
			}
		}
		
		/// <summary>
		/// Value of the Deemed Better Offer Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_deemedbetterofferamount_base")]
		public Microsoft.Xrm.Sdk.Money AAr_DeemedBetterOfferAmount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("aar_deemedbetterofferamount_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_disconnectionnonpayment")]
		public System.Nullable<bool> AAr_DisconnectionNonpayment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("aar_disconnectionnonpayment");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_disconnectionnonpayment", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_disconnectionnonpaymentname")]
		public string AAr_DisconnectionNonpaymentName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_disconnectionnonpayment"))
				{
					return this.FormattedValues["aar_disconnectionnonpayment"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_eligiblerefundamount")]
		public Microsoft.Xrm.Sdk.Money AAr_EligibleRefundAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("aar_eligiblerefundamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_eligiblerefundamount", value);
			}
		}
		
		/// <summary>
		/// Value of the Eligible Refund Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_eligiblerefundamount_base")]
		public Microsoft.Xrm.Sdk.Money AAr_EligibleRefundAmount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("aar_eligiblerefundamount_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_entrydate")]
		public System.Nullable<System.DateTime> AAr_EntryDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aar_entrydate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_entrydate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_familyviolence")]
		public System.Nullable<bool> AAr_FamilyViolence
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("aar_familyviolence");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_familyviolence", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_familyviolencename")]
		public string AAr_FamilyViolenceName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_familyviolence"))
				{
					return this.FormattedValues["aar_familyviolence"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_install")]
		public Microsoft.Xrm.Sdk.EntityReference AAr_Install
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("aar_install");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_install", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_installaddress")]
		public string AAr_InstallAddress
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_installaddress");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_installaddress", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_installfulladdress")]
		public string AAr_InstallFullAddress
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_installfulladdress");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_installname")]
		public string AAr_InstallName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_install"))
				{
					return this.FormattedValues["aar_install"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_installsitetype")]
		public virtual AAr_AccountType? AAr_InstallSiteType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((AAr_AccountType?)(EntityOptionSetEnum.GetEnum(this, "aar_installsitetype")));
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_installsitetypename")]
		public string AAr_InstallSiteTypeName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_installsitetype"))
				{
					return this.FormattedValues["aar_installsitetype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_invoicereference")]
		public string AAr_InvoiceReference
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_invoicereference");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_invoicereference", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_lastbilldate")]
		public System.Nullable<System.DateTime> AAr_LastBillDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aar_lastbilldate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_lastbilldate", value);
			}
		}
		
		/// <summary>
		/// To track the Address effective date, especially if customer has multiple addresses.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_lasteffectivedateofaddress")]
		public System.Nullable<System.DateTime> AAr_LastEffectiveDateOfAddress
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aar_lasteffectivedateofaddress");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_lasteffectivedateofaddress", value);
			}
		}
		
		/// <summary>
		/// Date the last invoice was issued
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_lastinvoicedate")]
		public System.Nullable<System.DateTime> AAr_LastInvoicedAte
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aar_lastinvoicedate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_lastinvoicedate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_lastmeterreaddate")]
		public System.Nullable<System.DateTime> AAr_LastMeterReaddAte
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aar_lastmeterreaddate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_lastmeterreaddate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_lastmeterreadtype")]
		public virtual AAr_MeterReadType? AAr_LastMeterReadType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((AAr_MeterReadType?)(EntityOptionSetEnum.GetEnum(this, "aar_lastmeterreadtype")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_lastmeterreadtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_lastmeterreadtypename")]
		public string AAr_LastMeterReadTypeName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_lastmeterreadtype"))
				{
					return this.FormattedValues["aar_lastmeterreadtype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_lifesupportrequired")]
		public virtual AAr_LifeSupportRequired? AAr_LifeSupportRequired
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((AAr_LifeSupportRequired?)(EntityOptionSetEnum.GetEnum(this, "aar_lifesupportrequired")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_lifesupportrequired", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_lifesupportrequiredname")]
		public string AAr_LifeSupportRequiredName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_lifesupportrequired"))
				{
					return this.FormattedValues["aar_lifesupportrequired"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_lpmerchant")]
		public Microsoft.Xrm.Sdk.EntityReference AAr_LpMerchant
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("aar_lpmerchant");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_lpmerchant", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_lpmerchantname")]
		public string AAr_LpMerchantName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_lpmerchant"))
				{
					return this.FormattedValues["aar_lpmerchant"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_managingofficer")]
		public string AAr_ManagingOfficer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_managingofficer");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_managingofficer", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_meterclass")]
		public string AAr_MeterClass
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_meterclass");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_meterclass", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_moveoutdate")]
		public System.Nullable<System.DateTime> AAr_MoveOutdate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aar_moveoutdate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_moveoutdate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_moveoutfeeswaived")]
		public virtual MSeVTmGt_NoOrYes? AAr_MoveOutFeesWaived
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((MSeVTmGt_NoOrYes?)(EntityOptionSetEnum.GetEnum(this, "aar_moveoutfeeswaived")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_moveoutfeeswaived", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_moveoutfeeswaivedname")]
		public string AAr_MoveOutFeesWaivedName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_moveoutfeeswaived"))
				{
					return this.FormattedValues["aar_moveoutfeeswaived"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_moveoutfinalbillemail")]
		public string AAr_MoveOutFinalBillEmail
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_moveoutfinalbillemail");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_moveoutfinalbillemail", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_moveoutfinalbillmethod")]
		public virtual AAr_CommunicationsPreference? AAr_MoveOutFinalBillMethod
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((AAr_CommunicationsPreference?)(EntityOptionSetEnum.GetEnum(this, "aar_moveoutfinalbillmethod")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_moveoutfinalbillmethod", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_moveoutfinalbillmethodname")]
		public string AAr_MoveOutFinalBillMethodName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_moveoutfinalbillmethod"))
				{
					return this.FormattedValues["aar_moveoutfinalbillmethod"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_moveoutfinalbillpostal")]
		public string AAr_MoveOutFinalBillPostal
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_moveoutfinalbillpostal");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_moveoutfinalbillpostal", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_moveoutnotes")]
		public string AAr_MoveOutNotes
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_moveoutnotes");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_moveoutnotes", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_moveoutreason")]
		public string AAr_MoveOutreason
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_moveoutreason");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_moveoutreason", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_networktariffcode")]
		public string AAr_NetworkTariffCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_networktariffcode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_networktariffcode", value);
			}
		}
		
		/// <summary>
		/// Date the next invoice will be issued
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_nextinvoicedate")]
		public System.Nullable<System.DateTime> AAr_NextInvoicedAte
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aar_nextinvoicedate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_nextinvoicedate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_nextpaymentduedate")]
		public System.Nullable<System.DateTime> AAr_NextPaymentDueDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aar_nextpaymentduedate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_nextpaymentduedate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_nextscheduledmeterread")]
		public System.Nullable<System.DateTime> AAr_NextScheduledMeterRead
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aar_nextscheduledmeterread");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_nextscheduledmeterread", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_nextstage")]
		public string AAr_NextStage
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_nextstage");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_nextstage", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_offer")]
		public Microsoft.Xrm.Sdk.EntityReference AAr_Offer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("aar_offer");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_offer", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_offername")]
		public string AAr_OfferName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_offer"))
				{
					return this.FormattedValues["aar_offer"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_paymentextensiondue")]
		public System.Nullable<System.DateTime> AAr_PaymentExtensionDue
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("aar_paymentextensiondue");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_paymentextensiondue", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_paymentextensioninplace")]
		public System.Nullable<bool> AAr_PaymentExtensionInPlace
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("aar_paymentextensioninplace");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_paymentextensioninplace", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_paymentextensioninplacename")]
		public string AAr_PaymentExtensionInPlaceName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_paymentextensioninplace"))
				{
					return this.FormattedValues["aar_paymentextensioninplace"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_paymentreference")]
		public string AAr_PaymentReference
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_paymentreference");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_paymentreference", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_pricingplan")]
		public string AAr_PricingPlan
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_pricingplan");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_pricingplan", value);
			}
		}
		
		/// <summary>
		/// The ID of the Principal Customer record for this Account in Velocity
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_principalcustomerid")]
		public string AAr_PrincipalCustomerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_principalcustomerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_principalcustomerid", value);
			}
		}
		
		/// <summary>
		/// The name of the Principal Customer record in Velocity
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_principalcustomername")]
		public string AAr_PrincipalCustomerName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_principalcustomername");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_principalcustomername", value);
			}
		}
		
		/// <summary>
		/// The risk score associated to the Account's Ledger
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_riskscore")]
		public string AAr_RiskScore
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_riskscore");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_riskscore", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_saleschannel")]
		public Microsoft.Xrm.Sdk.EntityReference AAr_SalesChannel
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("aar_saleschannel");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_saleschannel", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_saleschannelname")]
		public string AAr_SalesChannelName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_saleschannel"))
				{
					return this.FormattedValues["aar_saleschannel"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_signupapplication")]
		public Microsoft.Xrm.Sdk.EntityReference AAr_SignupApplication
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("aar_signupapplication");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_signupapplication", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_signupapplicationname")]
		public string AAr_SignupApplicationName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_signupapplication"))
				{
					return this.FormattedValues["aar_signupapplication"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_transactionhistoryurl")]
		public string AAr_TransactionHistoryUrl
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_transactionhistoryurl");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_transactionhistoryurl", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_usageatlastmeterread")]
		public System.Nullable<int> AAr_UsageAtLastMeterRead
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("aar_usageatlastmeterread");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_usageatlastmeterread", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_usageforsameperiodlastyear")]
		public System.Nullable<int> AAr_UsageForSamePeriodLastYear
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("aar_usageforsameperiodlastyear");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_usageforsameperiodlastyear", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_utilityservice")]
		public virtual AAr_UtilityType? AAr_UtilityService
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((AAr_UtilityType?)(EntityOptionSetEnum.GetEnum(this, "aar_utilityservice")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_utilityservice", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_utilityservicename")]
		public string AAr_UtilityServiceName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("aar_utilityservice"))
				{
					return this.FormattedValues["aar_utilityservice"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_velocitybestofferid")]
		public System.Nullable<int> AAr_VelocityBestOfferId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("aar_velocitybestofferid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_velocitybestofferid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_velocityconsumerid")]
		public string AAr_VelocityConsumerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_velocityconsumerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_velocityconsumerid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("aar_velocityledgerid")]
		public string AAr_VelocityLedgerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("aar_velocityledgerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("aar_velocityledgerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("createdonbehalfby", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the entity with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangerAte
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("modifiedonbehalfby", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Yomi name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
		public string OwningBusinessUnitName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("owningbusinessunit"))
				{
					return this.FormattedValues["owningbusinessunit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Account
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual AAr_Account_StateCode? StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((AAr_Account_StateCode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string StateCodename
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the Account
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual AAr_Account_StatusCode? StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((AAr_Account_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string StatusCodename
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("transactioncurrencyid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyidname")]
		public string TransactionCurrencyIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("transactioncurrencyid"))
				{
					return this.FormattedValues["transactioncurrencyid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UtcConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N aar_customerroles_Account_aar_account
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("aar_customerroles_Account_aar_account")]
		public System.Collections.Generic.IEnumerable<DataFlow.Dataverse.DataModel.AAr_CustomerRoles> AAr_CustomerRoles_Account_AAr_Account
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DataFlow.Dataverse.DataModel.AAr_CustomerRoles>("aar_customerroles_Account_aar_account", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntities<DataFlow.Dataverse.DataModel.AAr_CustomerRoles>("aar_customerroles_Account_aar_account", null, value);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public AAr_Account(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (value != null && name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["aar_accountid"] = base.Id;
                        break;
                    case "aar_accountid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}
#pragma warning restore CS1591
