#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFlow.Dataverse.DataModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum AAr_SmsBranding
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ActewAGL", 0)]
		Actewagl = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IconWater", 1)]
		Iconwater = 2,
	}
}
#pragma warning restore CS1591
