#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFlow.Dataverse.DataModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum AAr_AccountType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business", 1)]
		Business = 745620001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CNI", 2)]
		Cni = 745620002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Residential", 0)]
		Residential = 745620000,
	}
}
#pragma warning restore CS1591
