#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFlow.Dataverse.DataModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum AAr_UtilityType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Electricity", 0)]
		Electricity = 745620000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Gas", 1)]
		Gas = 745620001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("NA", 3)]
		Na = 745620003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Water", 2)]
		Water = 745620002,
	}
}
#pragma warning restore CS1591
