#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFlow.Dataverse.DataModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum AAr_MeterReadType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Actual", 1)]
		Actual = 745620001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Estimated", 0)]
		Estimated = 745620000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Stream", 2)]
		Stream = 745620002,
	}
}
#pragma warning restore CS1591
